### ISSUE TITLE
[Feature request] change title

### ISSUE THREAD

**Issue by HotarunIchijou** [thatsmanmeet/Tasky#16]
I think that title looks very annoying and rude, so text should be bigger with md.sys.color.on-secondary color and background with md.sys.color.secondary color. Also it should shrink on scroll, I think. Also I can make figma layout of this, if you like

**Comment by thatsmanmeet** [comment]
Please if you can then share a figma layout, that would help me understand what design are you looking for specifically.

**Comment by HotarunIchijou** [comment]
I've made the layout, check this out
https://www.figma.com/file/oasC1FtW3dI035V1PyfNQB/Tasky?node-id=0%3A1&t=4ikVD8GgkOrUcG78-1

Note that I couldn't make the shrinking title correctly, so that because I've made 2 frames

**Comment by HotarunIchijou** [comment]
Also maybe you should remove this floating date? I don't think that it's really needed

**Comment by thatsmanmeet** [comment]
> I've made the layout, check this out
> https://www.figma.com/file/oasC1FtW3dI035V1PyfNQB/Tasky?node-id=0%3A1&t=4ikVD8GgkOrUcG78-1
> 
> Note that I couldn't make the shrinking title correctly, so that because I've made 2 frames

Is it really necessary to move check boxes to the extreme right? The current design was also okay. Also there's a notification bell that shows on the extreme side in case a reminder is set.

**Comment by thatsmanmeet** [comment]
> Also maybe you should remove this floating date? I don't think that it's really needed

Well floating dates are to group multiple tasks that are on the same date. It is a good feature. What do you think ?

**Comment by HotarunIchijou** [comment]
> Is it really necessary to move check boxes to the extreme right?

No, it's not, it's just default position of assets, which I used, while did this project. but this arrangement can be comfortable for most people because they're right-handers

> Well floating dates are to group multiple tasks that are on the same date. It is a good feature. What do you think ?

Yes, but I think that fixed position also pretty good. I really have no idea, how to locate this floating date. You can see below previous position of this
![](https://user-images.githubusercontent.com/113282550/230719979-fc3463a1-af1e-40a4-8d7a-02aebecb26bc.jpg)
but this position didn't look good to me, so I had to move it to the application header, and so far it doesn't look good

**Comment by thatsmanmeet** [comment]
So, if you prefer the old view (without floating dates as with screenshots in my repo) then I will make a settings page for my app and provide a toggle to switch between new and old view of the app. Will that be okay for you ?

Also I have increased the textsize in the Top App Bar.

**Comment by HotarunIchijou** [comment]
> So, if you prefer the old view (without floating dates as with screenshots in my repo) then I will make a settings page for my app and provide a toggle to switch between new and old view of the app. Will that be okay for you?

Yes, that'll be fine

> Also I have increased the textsize in the Top App Bar. 

OK, but have you looked for color changes? Okay, but were you looking for color changes? I mean, I'm not only changed title background, but also tasks background

**Comment by thatsmanmeet** [comment]
> Okay, but were you looking for color changes? I mean, I'm not only changed title background, but also tasks background

Sure, you suggested secondary colors instead of primary ones. Here's some screenshots. 

![Screenshot_2023-04-08-18-04-03-409_com.thatsmanmeet.taskyapp.jpg](https://user-im![Screenshot_2023-04-08-18-04-52-200_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721381-674ae747-709c-41d2-9c89-ff9ba0d94749.jpg)

.jpg)

![Uploading Screenshot_2023-04-08-18-04-52-200_com.thatsmanmeet.taskyapp.jpg …]()

![Screenshot_2023-04-08-18-04-46-912_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721378-d396ec44-29a4-40ca-9546-e09359265648.jpg)

![Screenshot_2023-04-08-18-03-57-440_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721379-cecdd686-5668-48a3-ba2b-fd9547058f94.jpg)

Are these good or primary ones much better ?

**Comment by thatsmanmeet** [comment]
> Okay, but were you looking for color changes? I mean, I'm not only changed title background, but also tasks background

Sure, you suggested secondary colors instead of primary ones. Here's some screenshots. 

![Screenshot_2023-04-08-18-03-57-440_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721461-785246af-dd17-4f8b-a937-ec216987d514.jpg)

![Screenshot_2023-04-08-18-04-46-912_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721460-7716be19-351a-4add-9381-db94bde5d79e.jpg)

![Screenshot_2023-04-08-18-04-03-409_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721459-b390f127-3759-45d6-9c24-1e846952ed17.jpg)

![Screenshot_2023-04-08-18-04-52-200_com.thatsmanmeet.taskyapp.jpg](https://user-images.githubusercontent.com/120583077/230721462-3682b3de-bdd6-4b8f-9043-1a153d13b517.jpg)

These are some screenshots with secondary colors.

**Comment by HotarunIchijou** [comment]
But I suggested surface colors, and it's different, than the secondary one

**Comment by thatsmanmeet** [comment]
> But I suggested surface colors, and it's different, than the secondary one

> with md.sys.color.on-secondary color and background with md.sys.color.secondary color 

These were the one you asked mentioning secondary colors, if surface colors is what default app was using.

**Comment by HotarunIchijou** [comment]
Ok, as you wish
