### ISSUE TITLE
[Feature Request] Task with subtask

### ISSUE THREAD

**Issue by zoroya1** [thatsmanmeet/Tasky#8]
Currently user can add only one task and for subtask he has to make other tasks 

It will be great if one can make a main task with reminder and date with subtasks below it 

User can make a main task and by tapping it, subtasks will open

e.g : a grocery or supermarket as main task (reminder time x , date y)
And subtasks are onions, potatoes, oil etc. 

Also, bar for tasky app on top is somewhat big, can you reduce the length...

**Comment by thatsmanmeet** [comment]
I might add subtasks in future because I am planning a feature that might directly clash with subtask feature. I will keep this suggestion in mind and see if I can implement this or not with other feature.

As for the top appbar for the tasky basically it is of standard size like any other app however I have made the status bar and top app bar of the same color to make an integrated look, that's why it looks bigger. 

If you think that it's annoying to have that integrated status bar and appbar then I can provide a toggle in settings to give both of them different colors. What do you say ?

**Comment by zoroya1** [comment]
If you have another feature in mind that might clash with subtask feature than we willthe wait for subtasks :)

I think current colouring of app bar with status bar is good and enough as it is consistent with Material You Logic, i just wanted to suggest that space between Tasky font and status bar is more as it currently is, it wastes some space according to me, maybe reduce some space between the two ? 

Thanks for your considerarion and this awesome app 💙

**Comment by thatsmanmeet** [comment]
Sure, I will try to reduce length in upcoming release and thanks for your suggestions 🙏🏻
